# -*- coding: utf-8 -*-
"""LVADSUSR129_VenkataAbhishek_LAB1_IA1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JcWImstgBXMa93jBd8yZKUoVb2RoMR50
"""

import pandas as pd
df=pd.read_csv('/content/expenses.csv')
df.head()
df.tail()
df.info()

df.describe()

df.isna().sum()

df.head()

from scipy.stats import zscore
z_score = zscore(df)
print(z_score)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['sex']=label_encoder.fit_transform(df['sex'])
df['smoker']=label_encoder.fit_transform(df['smoker'])
#df['region']=label_encoder.fit_transform(df['region'])
df['charges']=label_encoder.fit_transform(df['charges'])

import warnings
warnings.filterwarnings("ignore")
correl=df.corr()
import matplotlib.pyplot as plt
plt.boxplot(correl)
plt.show()

import numpy as np
z_scores = zscore(df)
abs_z_scores = np.abs(z_scores)
filtered_entries = (abs_z_scores < 3).all(axis=1)
df_clean = df[filtered_entries]
print("Ol DF:\n")
print(df.shape)
print("DF after rmg outliers:")
print(df_clean.shape)

#df.drop_duplicates()
dup_rows = df.duplicated()
print(df[dup_rows])
del df['children']

del df['region']
del df['bmi']
df.head()

X=df.iloc[:,1:]
y=df.iloc[:,0]
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(X,y,test_size=0.3,random_state=555)

from sklearn.linear_model import LinearRegression
lnr=LinearRegression()
lnr.fit(train_x,train_y)
pr=lnr.predict(test_x)
#print(lnr.predict([[19,0,1,16884.92400]]))

from sklearn.metrics import mean_squared_error, r2_score
msne = mean_squared_error(test_y, pr)
print(msne)
sq_rt=np.sqrt(msne)
print(sq_rt)

r_2 = r2_score(test_y,pr)
print(r_2)